language: java
deploy:
  provider: heroku
  api_key:
    secure: bYpPkoNxwPJVLOBe1C45sRFFJ5qLE+JVkqMvzK56mYG1Y/jtTulYCyfZh7twq/2c41+zd0Q82qbwzOe/ScOUlpGZexem5avQgI1j3ActZToxbxe8j3o0H3XtDQiOy362e7U0G2+5oGoRk6zL4buMud74p4DICE4lHTxvcwccaKHiAfEEIx2slnjtR+ahgsjyYUWBgDbuaOhiewukNb+csaJC4dh4SmT2Hn661ptX5IbMHVEfbcwR4kxZUbaT8qwb9D15SKOj7kUonaGmppKK+eO8UsUamyzia8yxqkuxB40DFy/EJTY4z5/cjb+hL4bzFEV1eSJdhodrGFPK1p8OfnKonPymLrEC9ZEAOnwwIybxqF/BL+yILgjAPC3nWbYo/UUpDLj1Wp02vPmEm+lYL9n6VxSlyLcodzrwzDn/znTuK/QXYNcD8TSHhbeCK/nrqa0QOKRRyFRhVfcpeNzduxGNDibBEsc7xB3BB7fizFdWZ/rQYt56fEsG4a9Smbwa2cmQP+JOlVSVaZTah9UxAX0u4NoZ9+3U/wYDShcRjaeC9EKt0HqQNTmJNbPJY3QZSf2wIaf9nm250o0FALHl2yyP9/uNpbIEjCLa5fUkN3V6uY1jCDb0Aj4gnn+lx0jtZphab6nz662KjPlWUNnRAfU10n0lV1ZegIOeBioKAyM=
  app: sisteminha-backend
